### PR TITLE
Blog App: Controllers-Spec

### PR DESCRIPTION
**Pull request by mahdinoori2000**
What is added

- Add RSpec as a gem to the project.
- Create a Request spec file for all controllers.
- For each action:
- If the response status was correct.
- If a correct template was rendered.
- If the response body includes correct placeholder text.

### CODE REVIEW

**Review by brainconnect93 — CHANGES_REQUESTED** [review]
### Hi @Sammy3000, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Good Points 👍

- Descriptive Pull Request. ✔️
- Controller-spec implemented ✔️
- `user_spec.rb` & `post_spec.rb` file seen ✔️ 
- Good use of Git flow ✔️

### Changes Required

- [x] Hello @mahdinoori2000, great effort working on your project, but currently 26 out of 27 test cases in your project are failing and i would like you to work on it. I did a walk-through of the current behavior of your project in the video, kindly check it and act on the it

Video Demonstration 👇 

[screen-capture.webm](https://github.com/mahdinoori2000/blog-app/assets/78634841/c68d241b-ca48-41cf-b064-fd956560a483)


- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by KayLemba — CHANGES_REQUESTED** [review]
Hi @mahdinoori2000    👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
Git flow is followed. ✔️
Descriptive P.R
Professional README file 

Required Changes ♻️
Check the comments under the review in the inline comments.
 

- [x] As previously mentioned by the previous code reviewer your tests are failing it would be nice to correct this issue. Please kindly look at the screenshot below.

Screenshot 2023-12-09 at 6 35 09 PM
Kindly pay attention to detail to avoid wasting your review chance make sure everything works fine before submitting your work.


Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Review by Strangeal — COMMENTED** [review]
Hi @mahdinoori2000 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

Alt Text

 ## Required Changes ♻️
- [ ] Great job so far, However, as mentioned by the previous reviewers `26` out of `27` test cases in your project are failing and I would like you to work on it. Kindly make sure that all tests are passing before resubmitting your project for review.
Screenshot 2023-12-09 at 21 46 03

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by franclobo — CHANGES_REQUESTED** [review]
Hi @mahdinoori2000, 

# Required Changes ♻️

so-close-jim-halpert

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Good Constroller spec tests ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._


- [ ] Please 🙏🏽 correct your tests to pass them all as required by the previous code reviewer 👇🏽 

```ruby
Failures:

  1) Comment calls update_comments_counter after save
     Failure/Error: subject.save!
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (1, null, 3, null, 2023-12-09 22:13:38.818512, 2023-12-09 22:13:38.818512).
     # ./spec/comment_spec.rb:24:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (1, null, 3, null, 2023-12-09 22:13:38.818512, 2023-12-09 22:13:38.818512).
     #   ./spec/comment_spec.rb:24:in `block (2 levels) in <top (required)>'

  2) Comment increments comment_counter of associated post after save
     Failure/Error: subject.save!
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (2, null, 4, null, 2023-12-09 22:13:38.830306, 2023-12-09 22:13:38.830306).
     # ./spec/comment_spec.rb:30:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (2, null, 4, null, 2023-12-09 22:13:38.830306, 2023-12-09 22:13:38.830306).
     #   ./spec/comment_spec.rb:30:in `block (2 levels) in <top (required)>'

  3) Post Index Page should displays the user's profile picture
     Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (3, null, 5, Hi Tom Wonderful!, 2023-12-09 22:13:38.844501, 2023-12-09 22:13:38.844501).
     # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (3, null, 5, Hi Tom Wonderful!, 2023-12-09 22:13:38.844501, 2023-12-09 22:13:38.844501).
     #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  4) Post Index Page should displays the username
     Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (4, null, 6, Hi Tom Wonderful!, 2023-12-09 22:13:38.861014, 2023-12-09 22:13:38.861014).
     # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (4, null, 6, Hi Tom Wonderful!, 2023-12-09 22:13:38.861014, 2023-12-09 22:13:38.861014).
     #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  5) Post Index Page should displays the number of posts the user has written
     Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (5, null, 7, Hi Tom Wonderful!, 2023-12-09 22:13:38.875864, 2023-12-09 22:13:38.875864).
     # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (5, null, 7, Hi Tom Wonderful!, 2023-12-09 22:13:38.875864, 2023-12-09 22:13:38.875864).
     #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  6) Post Index Page should displays a post's title
     Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (6, null, 8, Hi Tom Wonderful!, 2023-12-09 22:13:38.890837, 2023-12-09 22:13:38.890837).
     # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (6, null, 8, Hi Tom Wonderful!, 2023-12-09 22:13:38.890837, 2023-12-09 22:13:38.890837).
     #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  7) Post Index Page should displays some of the post's body
     Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (7, null, 9, Hi Tom Wonderful!, 2023-12-09 22:13:38.905366, 2023-12-09 22:13:38.905366).
     # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (7, null, 9, Hi Tom Wonderful!, 2023-12-09 22:13:38.905366, 2023-12-09 22:13:38.905366).
     #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  8) Post Index Page should displays the first comments on a post
     Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (8, null, 10, Hi Tom Wonderful!, 2023-12-09 22:13:38.918326, 2023-12-09 22:13:38.918326).
     # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (8, null, 10, Hi Tom Wonderful!, 2023-12-09 22:13:38.918326, 2023-12-09 22:13:38.918326).
     #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  9) Post Index Page should displays how many comments a post has
     Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
     
     ActiveRecord::NotNullViolation:
       PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
       DETAIL:  Failing row contains (9, null, 11, Hi Tom Wonderful!, 2023-12-09 22:13:38.931421, 2023-12-09 22:13:38.931421).
     # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # PG::NotNullViolation:
     #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
     #   DETAIL:  Failing row contains (9, null, 11, Hi Tom Wonderful!, 2023-12-09 22:13:38.931421, 2023-12-09 22:13:38.931421).
     #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  10) Post Index Page should displays how many likes a post has
      Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (10, null, 12, Hi Tom Wonderful!, 2023-12-09 22:13:38.946361, 2023-12-09 22:13:38.946361).
      # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (10, null, 12, Hi Tom Wonderful!, 2023-12-09 22:13:38.946361, 2023-12-09 22:13:38.946361).
      #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  11) Post Index Page should displays a section for pagination if there are more posts than fit on the view
      Failure/Error: @comment1 = Comment.create(user: @user1, post: @first_post, text: 'Hi Tom Wonderful!')
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (11, null, 13, Hi Tom Wonderful!, 2023-12-09 22:13:38.960578, 2023-12-09 22:13:38.960578).
      # ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (11, null, 13, Hi Tom Wonderful!, 2023-12-09 22:13:38.960578, 2023-12-09 22:13:38.960578).
      #   ./spec/features/posts_index_spec.rb:9:in `block (2 levels) in <main>'

  12) Post show Page should displays the post title
      Failure/Error: @comment1 = Comment.create(post: @first_post, user: @user1, text: 'Hi Tom!, Nice comment')
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (12, null, 14, Hi Tom!, Nice comment, 2023-12-09 22:13:38.975781, 2023-12-09 22:13:38.975781).
      # ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (12, null, 14, Hi Tom!, Nice comment, 2023-12-09 22:13:38.975781, 2023-12-09 22:13:38.975781).
      #   ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'

  13) Post show Page should displays who author of the post
      Failure/Error: @comment1 = Comment.create(post: @first_post, user: @user1, text: 'Hi Tom!, Nice comment')
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (13, null, 15, Hi Tom!, Nice comment, 2023-12-09 22:13:38.990328, 2023-12-09 22:13:38.990328).
      # ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (13, null, 15, Hi Tom!, Nice comment, 2023-12-09 22:13:38.990328, 2023-12-09 22:13:38.990328).
      #   ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'

  14) Post show Page should displays how many comments it has
      Failure/Error: @comment1 = Comment.create(post: @first_post, user: @user1, text: 'Hi Tom!, Nice comment')
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (14, null, 16, Hi Tom!, Nice comment, 2023-12-09 22:13:39.003902, 2023-12-09 22:13:39.003902).
      # ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (14, null, 16, Hi Tom!, Nice comment, 2023-12-09 22:13:39.003902, 2023-12-09 22:13:39.003902).
      #   ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'

  15) Post show Page should displays how many likes it has
      Failure/Error: @comment1 = Comment.create(post: @first_post, user: @user1, text: 'Hi Tom!, Nice comment')
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (15, null, 17, Hi Tom!, Nice comment, 2023-12-09 22:13:39.017965, 2023-12-09 22:13:39.017965).
      # ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (15, null, 17, Hi Tom!, Nice comment, 2023-12-09 22:13:39.017965, 2023-12-09 22:13:39.017965).
      #   ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'

  16) Post show Page should displays the post body
      Failure/Error: @comment1 = Comment.create(post: @first_post, user: @user1, text: 'Hi Tom!, Nice comment')
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (16, null, 18, Hi Tom!, Nice comment, 2023-12-09 22:13:39.030625, 2023-12-09 22:13:39.030625).
      # ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (16, null, 18, Hi Tom!, Nice comment, 2023-12-09 22:13:39.030625, 2023-12-09 22:13:39.030625).
      #   ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'

  17) Post show Page should displays the username of  commentor
      Failure/Error: @comment1 = Comment.create(post: @first_post, user: @user1, text: 'Hi Tom!, Nice comment')
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (17, null, 19, Hi Tom!, Nice comment, 2023-12-09 22:13:39.044823, 2023-12-09 22:13:39.044823).
      # ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (17, null, 19, Hi Tom!, Nice comment, 2023-12-09 22:13:39.044823, 2023-12-09 22:13:39.044823).
      #   ./spec/features/posts_show_spec.rb:9:in `block (2 levels) in <main>'

  18) User Index Page should displays the username of all users
      Failure/Error: expect(page).to have_content(@user1.name)
        expected to find text "Sam" in "You need to sign in or sign up before continuing.\nLog in\nEmail\nPassword\nRemember me\nSign up Forgot your password? Didn't receive confirmation instructions?"
      # ./spec/features/users_index_spec.rb:12:in `block (2 levels) in <main>'

  19) User Index Page should displays the number of posts for each user
      Failure/Error: expect(page).to have_content(@user1.post_counter)
        expected to find text "1" in "You need to sign in or sign up before continuing.\nLog in\nEmail\nPassword\nRemember me\nSign up Forgot your password? Didn't receive confirmation instructions?". (However, it was found 32 times including non-visible text.)
      # ./spec/features/users_index_spec.rb:22:in `block (2 levels) in <main>'

  20) User Index Page should redirects to a user's show page when clicked on the name
      Failure/Error: click_link @user1.name
      
      Capybara::ElementNotFound:
        Unable to find link "Sam"
      # ./spec/features/users_index_spec.rb:27:in `block (2 levels) in <main>'

  21) User Show Page should displays the user's profile picture
      Failure/Error: expect(page).to have_css("img[src*='#{@user1.photo}']")
        expected to find css "img[src*='https://unsplash.com/photos']" but there were no matches
      # ./spec/features/users_show_spec.rb:19:in `block (2 levels) in <main>'

  22) User Show Page should displays the username
      Failure/Error: expect(page).to have_content(@user1.name)
        expected to find text "Tom" in "You need to sign in or sign up before continuing.\nLog in\nEmail\nPassword\nRemember me\nSign up Forgot your password? Didn't receive confirmation instructions?"
      # ./spec/features/users_show_spec.rb:23:in `block (2 levels) in <main>'

  23) User Show Page should displays the number of posts 
      Failure/Error: expect(page).to have_content(@user1.post_counter)
        expected to find text "4" in "You need to sign in or sign up before continuing.\nLog in\nEmail\nPassword\nRemember me\nSign up Forgot your password? Didn't receive confirmation instructions?". (However, it was found 30 times including non-visible text.)
      # ./spec/features/users_show_spec.rb:27:in `block (2 levels) in <main>'

  24) User Show Page should displays the user's bio
      Failure/Error: expect(page).to have_content(@user1.bio)
        expected to find text "Teacher from Mexico." in "You need to sign in or sign up before continuing.\nLog in\nEmail\nPassword\nRemember me\nSign up Forgot your password? Didn't receive confirmation instructions?"
      # ./spec/features/users_show_spec.rb:31:in `block (2 levels) in <main>'

  25) User Show Page should displays the first 3 posts
      Failure/Error: expect(post_elements.count).to eq(3)
      
        expected: 3
             got: 0
      
        (compared using ==)
      # ./spec/features/users_show_spec.rb:36:in `block (2 levels) in <main>'

  26) User Show Page should display a button that let view all of a user's posts.
      Failure/Error: expect(page).to have_link('See All Posts')
        expected to find link "See All Posts" but there were no matches
      # ./spec/features/users_show_spec.rb:40:in `block (2 levels) in <main>'

  27) User Show Page redirects to a user's post index page when 'View All Posts' button is clicked
      Failure/Error: click_link 'See All Posts'
      
      Capybara::ElementNotFound:
        Unable to find link "See All Posts"
      # ./spec/features/users_show_spec.rb:44:in `block (2 levels) in <main>'

  28) User Show Page redirects to a user's post show page when clicking a post
      Failure/Error: click_link 'post4'
      
      Capybara::ElementNotFound:
        Unable to find link "post4"
      # ./spec/features/users_show_spec.rb:49:in `block (2 levels) in <main>'

  29) Like update_likes_counter method increments the like counter of the associated post
      Failure/Error: like.save!
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "likes" violates not-null constraint
        DETAIL:  Failing row contains (1, null, 52, 2023-12-09 22:13:41.090432, 2023-12-09 22:13:41.090432).
      # ./spec/like_spec.rb:25:in `block (4 levels) in <main>'
      # ./spec/like_spec.rb:19:in `block (3 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "likes" violates not-null constraint
      #   DETAIL:  Failing row contains (1, null, 52, 2023-12-09 22:13:41.090432, 2023-12-09 22:13:41.090432).
      #   ./spec/like_spec.rb:25:in `block (4 levels) in <main>'

  30) Post recent_comments method returns the 5 most recent comments
      Failure/Error: comments.each(&:save!)
      
      ActiveRecord::NotNullViolation:
        PG::NotNullViolation: ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
        DETAIL:  Failing row contains (18, null, 53, Comment 1, 2023-12-09 22:13:41.119735, 2023-12-09 22:13:41.119735).
      # ./spec/post_spec.rb:60:in `each'
      # ./spec/post_spec.rb:60:in `block (4 levels) in <main>'
      # ./spec/post_spec.rb:48:in `block (3 levels) in <main>'
      # ------------------
      # --- Caused by: ---
      # PG::NotNullViolation:
      #   ERROR:  null value in column "user_id" of relation "comments" violates not-null constraint
      #   DETAIL:  Failing row contains (18, null, 53, Comment 1, 2023-12-09 22:13:41.119735, 2023-12-09 22:13:41.119735).
      #   ./spec/post_spec.rb:60:in `each'

  31) User recent_posts method returns the 3 most recent posts
      Failure/Error: user.posts.create(title: 'Post 1'),
      
      ActiveRecord::RecordNotSaved:
        You cannot call create unless the parent is saved
      # ./spec/user_spec.rb:49:in `block (3 levels) in <main>'

Finished in 2.49 seconds (files took 3.28 seconds to load)
50 examples, 31 failures
```

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
